development:
  dialect: postgres
  datasource: host=db port=5432 dbname=api user=postgresql password=postgresql sslmode=disable
  dir: db/migrations
  table: migrations

test:
  dialect: postgres
  datasource: host=test-db port=25432 dbname=test-api user=postgresql password=postgresql sslmode=disable
  dir: db/migrations
  table: migrations
